# Generated by Django 5.1.4 on 2024-12-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newscategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsCategory',
        ),
    ]
