# Generated by Django 5.1.4 on 2024-12-18 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_delete_newscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='news',
            name='author_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
