# Generated by Django 5.1.4 on 2024-12-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_add_date_news_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='add_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='news',
            name='author_name',
            field=models.CharField(max_length=200),
        ),
    ]
